import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {FwdButton} from '../components/components';
import HeaderItem from '../components/HeaderItem';
import {HomeIcon} from '@heroicons/react/outline';
 
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Remote selling</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <head className={styles.header + ' bg-fwd'}>
        <HeaderItem title="Home" Icon={HomeIcon}> </HeaderItem>
        <HeaderItem title="Home" Icon={HomeIcon}> </HeaderItem>
      </head>

      <main className={styles.main}>
      <div className="p-6 max-w-sm mx-auto bg-white rounded-xl shadow-md flex items-center space-x-4">
          <FwdButton>XXX</FwdButton>
        <div>
          <div className="text-xl font-medium bg-yellow-700 md:bg-green-200">ChitChat</div>
          <p className="bg-blue">You have a new message!s</p>
          
        </div>
      </div>
      <FwdButton default className="bg-blue-100">
          Next
        </FwdButton>
      </main>

      <footer className={styles.footer}>
        <h1>Testing</h1>
        <FwdButton default className="bg-yellow-100">
          Next
        </FwdButton>
      </footer>
    </div>
  )
}
